export const CREATE_TASKS_LIST = 'CREATE_TASKS_LIST';
export const CREATE_NEW_TASK = 'CREATE_NEW_TASK';
export const UPDATE_TASKS_LIST = 'UPDATE_TASKS_LIST';
export const REMOVE_TASK_FROM_LIST = 'REMOVE_TASK_FROM_LIST';
export const TOGGLE_TASK = 'TOGGLE_TASK';

export const CREATE_NOTES_LIST = 'CREATE_NOTES_LIST';
export const CREATE_NEW_NOTE = 'CREATE_NEW_NOTE';
export const UPDATE_NOTES_LIST = 'UPDATE_NOTES_LIST';
export const REMOVE_NOTE_FROM_LIST = 'REMOVE_NOTE_FROM_LIST';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const TASK_INCREMENT = 'TASK_INCREMENT';
export const TASK_DECREMENT = 'TASK_DECREMENT';
